<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'BaconAssetLoader\Asset\Manager'      => __DIR__ . '/src/BaconAssetLoader/Asset/Manager.php',
    'BaconAssetLoader\Asset\MimeDetector' => __DIR__ . '/src/BaconAssetLoader/Asset/MimeDetector.php',
    'BaconAssetLoader\Asset\Collection'   => __DIR__ . '/src/BaconAssetLoader/Asset/Collection.php',
    'BaconAssetLoader\Asset\File'         => __DIR__ . '/src/BaconAssetLoader/Asset/File.php',
    'BaconAssetLoader\Module'             => __DIR__ . '/Module.php',
);